image: docker:latest
services:
- docker:dind

stages:
- build
- release

variables:
  TEST_IMAGE: git.adr3nalin3.net:4567/dleahy/docker-phpaste:$CI_COMMIT_REF_NAME
  RELEASE_IMAGE: git.adr3nalin3.net:4567/dleahy/docker-phpaste:latest
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN git.adr3nalin3.net:4567

build:
  stage: build
  script:
    - docker build --pull -t $TEST_IMAGE .
    - docker push $TEST_IMAGE

release:
  stage: release
  script:
    - docker pull $TEST_IMAGE
    - docker tag $TEST_IMAGE $RELEASE_IMAGE
    - docker push $TEST_IMAGE
    - docker push $RELEASE_IMAGE
  only:
    - master
