---
version: "2"
services:
  screenshot-upload:
    image: git.adr3nalin3.net:4567/dleahy/docker-phpaste:latest
    container_name: screenshot-upload
    ports:
      - 32881:80
    restart: unless-stopped
