---
version: "2"
services:
  paste:
    image: dwaan/docker-phpaste:latest
    container_name: paste
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./www:/www:rw
  mysql:
    image: mysql:latest
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: paste
    volumes:
      - ./data_mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d
