---
version: "2"
services:
  screenshot-upload:
    image: git.adr3nalin3.net:4567/dleahy/docker-phpaste:master
    container_name: screenshot-upload
    ports:
      - 80:80
    restart: unless-stopped
    volumes:
      - ./config.php:/www/config.php
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_ROOT_USER: root
      MYSQL_DATABASE: paste
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - ./data_mysql:/var/lib/mysql
      - ./sql:/docker-entrypoint-initdb.d