---
version: "2"
services:
  screenshot-upload:
    image: git.adr3nalin3.net:4567/dleahy/docker-phpaste:latest
    container_name: screenshot-upload
    ports:
      - 32881:80
    restart: unless-stopped
  mysql:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./data_mysql:/var/lib/mysql